/*
 * Copyright (c) 2025, Oracle and/or its affiliates.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at https://opensource.org/license/UPL.
 */

package com.example.metacircular;

import com.dylibso.chicory.runtime.ByteArrayMemory;
import com.dylibso.chicory.runtime.ExportFunction;
import com.dylibso.chicory.runtime.HostFunction;
import com.dylibso.chicory.runtime.ImportValues;
import com.dylibso.chicory.runtime.Instance;
import com.dylibso.chicory.runtime.WasmArray;
import com.dylibso.chicory.runtime.WasmException;
import com.dylibso.chicory.runtime.WasmFunctionHandle;
import com.dylibso.chicory.runtime.WasmGcRef;
import com.dylibso.chicory.runtime.WasmStruct;
import com.dylibso.chicory.wasm.WasmModule;
import com.dylibso.chicory.wasm.types.FunctionImport;
import com.dylibso.chicory.wasm.types.FunctionType;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Runs WebImage-compiled javac back in Chicory on the JVM.
 *
 * Import implementations are modeled after the JS glue code in javac.js
 * generated by GraalVM WebImage.
 */
public class JavacRunner {

    // --- externref store: long <-> Object ---
    // StoreRef IDs are small positive numbers (< 0x10000).
    // GC ref handles are >= 0x10000. This distinction is important for routing values.
    static final Map<Long, Object> REFS = new ConcurrentHashMap<>();
    // Start at a high value to avoid collisions with Chicory's GC ref table indices.
    // any.convert_extern is a no-op in Chicory, so extern.wrap(storeRefId) does
    // ref.test(gcRef(storeRefId)) — if storeRefId collides with a valid GC index,
    // extern.wrap returns the wrong object instead of creating a WasmExtern wrapper.
    static final AtomicLong REF_SEQ = new AtomicLong(0x7F_000_000L); // 0 = null

    static long storeRef(Object obj) {
        if (obj == null) return 0;
        long id = REF_SEQ.getAndIncrement();
        REFS.put(id, obj);
        return id;
    }

    static Object loadRef(long id) {
        if (id == 0) return null;
        return REFS.get(id);
    }

    static final long[] EMPTY = new long[0];
    static final StringBuilder STDOUT_BUFFER = new StringBuilder();

    @SuppressWarnings("unchecked")
    public static void main(String[] args) throws IOException {
        // Read .java file from disk and prepare args for Wasm module
        String[] wasmArgs;
        if (args.length >= 1 && args[0].endsWith(".java")) {
            Path javaFile = Path.of(args[0]);
            String source = Files.readString(javaFile);
            String basename = javaFile.getFileName().toString();
            wasmArgs = new String[] {basename, source};
            System.err.println("Compiling " + javaFile + " via Wasm javac...");
        } else {
            wasmArgs = args;
            System.err.println("Loading WebImage-compiled javac in Chicory...");
        }

        var module = Javac.load();

        // Resolve function types from imports
        var importSection = module.importSection();
        Map<String, FunctionType> importTypes = new HashMap<>();
        for (int i = 0; i < importSection.importCount(); i++) {
            var imp = importSection.getImport(i);
            if (imp instanceof FunctionImport fi) {
                importTypes.put(imp.name(), module.typeSection().getType(fi.typeIndex()));
            }
        }

        var allFunctions =
                java.util.stream.Stream.<HostFunction>of(
                                // --- interop ---
                                fni(
                                        "interop",
                                        "genBacktrace",
                                        importTypes,
                                        (inst, a) -> new long[] {storeRef("")}),
                                fni(
                                        "interop",
                                        "Date.now",
                                        importTypes,
                                        (inst, a) ->
                                                new long[] {
                                                    Double.doubleToRawLongBits(
                                                            (double) System.currentTimeMillis())
                                                }),
                                fni(
                                        "interop",
                                        "performance.now",
                                        importTypes,
                                        (inst, a) ->
                                                new long[] {
                                                    Double.doubleToRawLongBits(
                                                            System.nanoTime() / 1_000_000.0)
                                                }),
                                fni(
                                        "interop",
                                        "getCurrentWorkingDirectory",
                                        importTypes,
                                        (inst, a) ->
                                                new long[] {
                                                    javaStringToGcRef(
                                                            inst,
                                                            System.getProperty("user.dir", "."))
                                                }),

                                // --- javac-specific: file I/O ---
                                // JS ref: return fs.readFileSync(path, {encoding: "utf-8"});
                                // path is a JS string, returns a JS string
                                fnf(
                                        "jsbody",
                                        module,
                                        "readFile",
                                        importTypes,
                                        (inst, a) -> {
                                            var pathStr = jsValueToString(inst, a[1]);
                                            try {
                                                String content = Files.readString(Path.of(pathStr));
                                                return new long[] {
                                                    storeRef(content)
                                                }; // return as JS string
                                            } catch (IOException e) {
                                                throw new RuntimeException(
                                                        "Failed to read: " + pathStr, e);
                                            }
                                        }),
                                // JS ref: fs.writeFileSync(path, buf);
                                fnf(
                                        "jsbody",
                                        module,
                                        "writeFile",
                                        importTypes,
                                        (inst, a) -> {
                                            var pathStr = jsValueToString(inst, a[1]);
                                            // a[2] is a JS object (HashMap in our model)
                                            var jsObj = jsValueToObject(inst, a[2]);
                                            if (jsObj instanceof Map<?, ?> map) {
                                                int length = toInt(map.get("length"));
                                                byte[] bytes = new byte[length];
                                                for (int i = 0; i < length; i++) {
                                                    bytes[i] = toByte(map.get(i));
                                                }
                                                try {
                                                    Path out = Path.of(pathStr);
                                                    if (out.getParent() != null)
                                                        Files.createDirectories(out.getParent());
                                                    Files.write(out, bytes);
                                                    System.out.println("Wrote: " + out);
                                                } catch (IOException e) {
                                                    throw new RuntimeException(
                                                            "Failed to write: " + pathStr, e);
                                                }
                                            }
                                            return new long[] {-1}; // void
                                        }),

                                // --- FileSystemInitializer ---
                                fni(
                                        "jsbody",
                                        "_FileSystemInitializer.prefetchedLibraryNames___JSObject",
                                        importTypes,
                                        (inst, a) -> {
                                            // Return a JS array-like object with length=0
                                            Map<Object, Object> arr = new HashMap<>();
                                            arr.put("length", 0);
                                            return new long[] {storeRef(arr)};
                                        }),
                                fni(
                                        "jsbody",
                                        "_FileSystemInitializer.prefetchedLibraryContent___String_String",
                                        importTypes,
                                        (inst, a) -> new long[] {storeRef("undefined")}),
                                fni(
                                        "jsbody",
                                        "_FileSystemInitializer.clearPrefetchedLibraryContent___String_V",
                                        importTypes,
                                        (inst, a) -> new long[] {-1}),

                                // --- JSFunctionIntrinsics ---
                                // JS ref: return o === undefined;
                                fnf(
                                        "jsbody",
                                        module,
                                        "isUndefined",
                                        importTypes,
                                        (inst, a) -> {
                                            Object val = loadRef(a[1]);
                                            boolean isUndef =
                                                    val == null && a[1] == 0
                                                            || "undefined".equals(val)
                                                            || val instanceof String s
                                                                    && s.equals("undefined");
                                            return new long[] {isUndef ? 1 : 0};
                                        }),

                                // --- JSConversion ---
                                // JS ref: return conversion.javaScriptToJava(x);
                                // Converts JS value → Java type using extern.wrap +
                                // convert.create.js*
                                fnf(
                                        "jsbody",
                                        module,
                                        "javaScriptToJava",
                                        importTypes,
                                        (inst, a) -> {
                                            long externRef = a[1];
                                            if (externRef == -1 || externRef == 0)
                                                return new long[] {externRef}; // null
                                            Object val = loadRef(externRef);
                                            // Not in our store → probably a GC ref, pass through
                                            if (val == null) return new long[] {externRef};
                                            // Wrap the externref via extern.wrap, then create the
                                            // appropriate JS type
                                            ExportFunction wrapExtern = inst.export("extern.wrap");
                                            long wrapped = wrapExtern.apply(externRef)[0];
                                            // Check undefined BEFORE String (since "undefined" is
                                            // also instanceof String)
                                            if ("undefined".equals(val)) {
                                                return new long[] {
                                                    inst.export("convert.create.jsundefined")
                                                            .apply()[0]
                                                };
                                            }
                                            if (val instanceof String) {
                                                return new long[] {
                                                    inst.export("convert.create.jsstring")
                                                            .apply(wrapped)[0]
                                                };
                                            }
                                            if (val instanceof Map) {
                                                return new long[] {
                                                    inst.export("convert.create.jsobject")
                                                            .apply(wrapped)[0]
                                                };
                                            }
                                            if (val instanceof Number n) {
                                                // Store the double in externref store, wrap it,
                                                // create JSNumber
                                                long numRef = storeRef(n.doubleValue());
                                                long numWrapped = wrapExtern.apply(numRef)[0];
                                                return new long[] {
                                                    inst.export("convert.create.jsnumber")
                                                            .apply(numWrapped)[0]
                                                };
                                            }
                                            if (val instanceof Boolean) {
                                                return new long[] {
                                                    inst.export("convert.create.jsboolean")
                                                            .apply(wrapped)[0]
                                                };
                                            }
                                            // Default: wrap as JSObject
                                            return new long[] {
                                                inst.export("convert.create.jsobject")
                                                        .apply(wrapped)[0]
                                            };
                                        }),
                                // JS ref: return conversion.unproxy(proxy);
                                // In our model we don't use JS proxies, just pass through
                                fnf(
                                        "jsbody",
                                        module,
                                        "unproxy",
                                        importTypes,
                                        (inst, a) -> new long[] {a[1]}),
                                // JS ref: return conversion.extractJavaScriptString(s);
                                // Extracts JS string from a Java String
                                fnf(
                                        "jsbody",
                                        module,
                                        "extractJavaScriptString",
                                        importTypes,
                                        (inst, a) -> {
                                            String s = jsValueToString(inst, a[1]);
                                            return new long[] {storeRef(s)};
                                        }),
                                // JS ref: return conversion.toProxy(self);
                                // In our model, just pass through
                                fnf(
                                        "jsbody",
                                        module,
                                        "extractJavaScriptProxy",
                                        importTypes,
                                        (inst, a) -> new long[] {a[1]}),
                                // JS ref: return undefined;
                                fnf(
                                        "jsbody",
                                        module,
                                        "javaScriptUndefined",
                                        importTypes,
                                        (inst, a) -> new long[] {storeRef("undefined")}),
                                // JS ref: return conversion.isInternalJavaObject(obj) ? obj :
                                // toJavaString(obj.toString());
                                fnf(
                                        "jsbody",
                                        module,
                                        "asJavaObjectOrString",
                                        importTypes,
                                        (inst, a) -> {
                                            long externRef = a[1];
                                            if (externRef == -1 || externRef == 0)
                                                return new long[] {externRef};
                                            Object val = loadRef(externRef);
                                            // Not in our store → probably a GC ref, pass through
                                            if (val == null) return new long[] {externRef};
                                            if (val instanceof String s) {
                                                return new long[] {javaStringToGcRef(inst, s)};
                                            }
                                            return new long[] {externRef};
                                        }),

                                // --- JSObject ---
                                // JS ref: return {};
                                fnf(
                                        "jsbody",
                                        module,
                                        "JSObject.create",
                                        importTypes,
                                        (inst, a) ->
                                                new long[] {
                                                    storeRef(new HashMap<Object, Object>())
                                                }),
                                // JS ref: this[key] = newValue;
                                fnf(
                                        "jsbody",
                                        module,
                                        "JSObject.set",
                                        importTypes,
                                        (inst, a) -> {
                                            var obj = jsValueToObject(inst, a[0]);
                                            var key = jsValueToString(inst, a[1]);
                                            var val = jsValueToObject(inst, a[2]);
                                            if (obj instanceof Map map) {
                                                map.put(key, val);
                                            }
                                            return new long[] {-1};
                                        }),
                                // JS ref: return this[key];
                                fnf(
                                        "jsbody",
                                        module,
                                        "_JSObject.get",
                                        importTypes,
                                        (inst, a) -> {
                                            var obj = jsValueToObject(inst, a[0]);
                                            // Key may be a GC String ref — use jsValueToString for
                                            // reliable extraction
                                            var key = jsValueToString(inst, a[1]);
                                            if (obj instanceof Map<?, ?> map) {
                                                Object result = map.get(key);
                                                if (result == null)
                                                    return new long[] {storeRef("undefined")};
                                                if (result instanceof Long l)
                                                    return new long[] {l}; // already an externref
                                                return new long[] {storeRef(result)};
                                            }
                                            return new long[] {storeRef("undefined")};
                                        }),
                                // JS ref: return typeof this;
                                fnf(
                                        "jsbody",
                                        module,
                                        "typeofString",
                                        importTypes,
                                        (inst, a) -> {
                                            Object val = jsValueToObject(inst, a[0]);
                                            String type =
                                                    (val instanceof Map)
                                                            ? "object"
                                                            : (val instanceof String)
                                                                    ? "string"
                                                                    : (val instanceof Number)
                                                                            ? "number"
                                                                            : (val
                                                                                            instanceof
                                                                                            Boolean)
                                                                                    ? "boolean"
                                                                                    : "object";
                                            return new long[] {storeRef(type)};
                                        }),

                                // --- JSString ---
                                // JS ref: return
                                // conversion.extractJavaScriptString(conversion.unproxy(s));
                                // Extracts a JS string from the Java String argument
                                fni(
                                        "jsbody",
                                        "_JSString.of___String_JSString",
                                        importTypes,
                                        (inst, a) -> {
                                            // a[1] = Java String ref; extract the string content
                                            String s = jsValueToString(inst, a[1]);
                                            return new long[] {
                                                storeRef(s)
                                            }; // return JS string externref
                                        }),
                                // JS ref: return conversion.toProxy(toJavaString(this));
                                // Converts the JS string back to a Java String GC struct
                                fni(
                                        "jsbody",
                                        "_JSString.asString___String",
                                        importTypes,
                                        (inst, a) -> {
                                            // a[0] = this (JS string externref)
                                            String s = jsValueToString(inst, a[0]);
                                            return new long[] {javaStringToGcRef(inst, s)};
                                        }),

                                // --- JSNumber ---
                                // JS ref: return
                                // conversion.extractJavaScriptNumber(conversion.unproxy(d));
                                fnf(
                                        "jsbody",
                                        module,
                                        "_JSNumber.of",
                                        importTypes,
                                        (inst, a) -> {
                                            // a[1] is a Java Double GC ref; extract the double via
                                            // unbox.double export
                                            long raw = inst.export("unbox.double").apply(a[1])[0];
                                            return new long[] {
                                                storeRef(Double.longBitsToDouble(raw))
                                            };
                                        }),
                                // JS ref: return
                                // conversion.toProxy(conversion.createJavaDouble(this));
                                fnf(
                                        "jsbody",
                                        module,
                                        "_JSNumber.javaDouble",
                                        importTypes,
                                        (inst, a) -> {
                                            // a[0] = this (JS number externref)
                                            Object val = loadRef(a[0]);
                                            if (val instanceof Number n) {
                                                return new long[] {
                                                    inst.export("box.double")
                                                            .apply(d2l(n.doubleValue()))[0]
                                                };
                                            }
                                            return new long[] {
                                                inst.export("box.double").apply(d2l(0.0))[0]
                                            };
                                        }),

                                // --- JSBoolean ---
                                // JS ref: return
                                // conversion.toProxy(conversion.createJavaBoolean(this));
                                fnf(
                                        "jsbody",
                                        module,
                                        "javaBoolean",
                                        importTypes,
                                        (inst, a) -> {
                                            Object val = loadRef(a[0]);
                                            if (val instanceof Boolean b) {
                                                return new long[] {
                                                    inst.export("box.boolean").apply(b ? 1 : 0)[0]
                                                };
                                            }
                                            return new long[] {
                                                inst.export("box.boolean").apply(0)[0]
                                            };
                                        }),

                                // --- JSSymbol ---
                                // JS ref: return sym0 === sym1;
                                fnf(
                                        "jsbody",
                                        module,
                                        "referenceEquals",
                                        importTypes,
                                        (inst, a) -> new long[] {a[0] == a[1] ? 1 : 0}),

                                // --- JSValue ---
                                // JS ref: return this?.toString() ?? 'undefined';
                                fni(
                                        "jsbody",
                                        "_JSValue.stringValue___String",
                                        importTypes,
                                        (inst, a) -> {
                                            Object val = jsValueToObject(inst, a[0]);
                                            String s = (val != null) ? val.toString() : "undefined";
                                            return new long[] {storeRef(s)};
                                        }),

                                // --- WebImageUtil ---
                                // JS ref: return Math.random();
                                fnf(
                                        "jsbody",
                                        module,
                                        "random",
                                        importTypes,
                                        (inst, a) -> new long[] {d2l(Math.random())}),

                                // --- compat math ---
                                fni(
                                        "compat",
                                        "f64log",
                                        importTypes,
                                        (inst, a) -> new long[] {d2l(Math.log(l2d(a[0])))}),
                                fni(
                                        "compat",
                                        "f64log10",
                                        importTypes,
                                        (inst, a) -> new long[] {d2l(Math.log10(l2d(a[0])))}),
                                fni(
                                        "compat",
                                        "f64pow",
                                        importTypes,
                                        (inst, a) ->
                                                new long[] {d2l(Math.pow(l2d(a[0]), l2d(a[1])))}),
                                fni(
                                        "compat",
                                        "f64rem",
                                        importTypes,
                                        (inst, a) -> new long[] {d2l(l2d(a[0]) % l2d(a[1]))}),
                                fni(
                                        "compat",
                                        "f32rem",
                                        importTypes,
                                        (inst, a) -> {
                                            float x = Float.intBitsToFloat((int) a[0]);
                                            float y = Float.intBitsToFloat((int) a[1]);
                                            return new long[] {Float.floatToRawIntBits(x % y)};
                                        }),

                                // --- convert ---
                                fni(
                                        "convert",
                                        "proxyCharArray",
                                        importTypes,
                                        (inst, a) -> {
                                            WasmGcRef ref = inst.gcRef((int) a[0]);
                                            if (ref instanceof WasmStruct s) {
                                                long arrayRef = s.field(2);
                                                WasmGcRef arrGc = inst.gcRef((int) arrayRef);
                                                if (arrGc instanceof WasmArray arr) {
                                                    char[] chars = new char[arr.length()];
                                                    for (int i = 0; i < chars.length; i++) {
                                                        chars[i] = (char) (arr.get(i) & 0xFFFF);
                                                    }
                                                    return new long[] {storeRef(chars)};
                                                }
                                            }
                                            return new long[] {storeRef(new char[0])};
                                        }),

                                // --- interop I/O ---
                                fni(
                                        "interop",
                                        "stdoutWriter.printChars",
                                        importTypes,
                                        (inst, a) -> {
                                            var obj = loadRef(a[0]);
                                            if (obj instanceof char[] chars)
                                                STDOUT_BUFFER.append(new String(chars));
                                            else if (obj instanceof String s)
                                                STDOUT_BUFFER.append(s);
                                            else if (obj != null) STDOUT_BUFFER.append(obj);
                                            return EMPTY;
                                        }),
                                fni(
                                        "interop",
                                        "stderrWriter.printChars",
                                        importTypes,
                                        (inst, a) -> {
                                            var obj = loadRef(a[0]);
                                            if (obj instanceof char[] chars)
                                                System.err.print(new String(chars));
                                            else if (obj instanceof String s) System.err.print(s);
                                            else if (obj != null) System.err.print(obj);
                                            return EMPTY;
                                        }),
                                fni(
                                        "interop",
                                        "stderrWriter.flush",
                                        importTypes,
                                        (inst, a) -> {
                                            System.err.flush();
                                            return EMPTY;
                                        }),
                                fni(
                                        "interop",
                                        "stdoutWriter.flush",
                                        importTypes,
                                        (inst, a) -> {
                                            System.out.flush();
                                            return EMPTY;
                                        }),

                                // --- interop misc ---
                                fni(
                                        "interop",
                                        "llog",
                                        importTypes,
                                        (inst, a) -> {
                                            System.err.println("[wasm:log] " + loadRef(a[0]));
                                            return EMPTY;
                                        }),
                                fni(
                                        "interop",
                                        "formatStackTrace",
                                        importTypes,
                                        (inst, a) ->
                                                new long[] {
                                                    javaStringToGcRef(inst, "<stack trace>")
                                                }),
                                fni(
                                        "interop",
                                        "stdoutWriter.close",
                                        importTypes,
                                        (inst, a) -> EMPTY),
                                fni(
                                        "interop",
                                        "stderrWriter.close",
                                        importTypes,
                                        (inst, a) -> EMPTY),
                                fni(
                                        "interop",
                                        "runtime.setExitCode",
                                        importTypes,
                                        (inst, a) -> {
                                            System.err.println("[wasm] exit code: " + a[0]);
                                            return EMPTY;
                                        }))
                        .filter(java.util.Objects::nonNull)
                        .toArray(HostFunction[]::new);
        var imports = ImportValues.builder().addFunction(allFunctions).build();

        var instance =
                Instance.builder(module)
                        .withImportValues(imports)
                        .withMachineFactory(Javac::create)
                        .withMemoryFactory(ByteArrayMemory::new)
                        .build(); // run start function for WebImage runtime init

        System.err.println("Instance created. Calling main...");

        var arrayStringCreate = instance.export("array.string.create");
        var arrayObjectWrite = instance.export("array.object.write");
        long stringArray = arrayStringCreate.apply(wasmArgs.length)[0];
        for (int i = 0; i < wasmArgs.length; i++) {
            arrayObjectWrite.apply(stringArray, i, javaStringToGcRef(instance, wasmArgs[i]));
        }

        var mainFn = instance.export("main");
        try {
            long exitCode = mainFn.apply(stringArray)[0];
            System.err.println("Done. Exit code: " + exitCode);
        } catch (WasmException we) {
            System.err.println(
                    "WasmException: tagIdx="
                            + we.tagIdx()
                            + " args="
                            + java.util.Arrays.toString(we.args()));
            System.err.println("Stack trace depth: " + we.getStackTrace().length);
            for (StackTraceElement ste : we.getStackTrace()) {
                System.err.println("  at " + ste);
            }
            if (we.getCause() != null) {
                System.err.println("Caused by: " + we.getCause());
                we.getCause().printStackTrace(System.err);
            }
            long excRef = we.args()[0];
            // Try to extract the exception class name and message
            try {
                WasmGcRef excGc = instance.gcRef((int) excRef);
                if (excGc instanceof WasmStruct excStruct) {
                    // Try to get class name from vtable/hub (field 0)
                    try {
                        long hubRef = excStruct.field(0);
                        WasmGcRef hubGc = instance.gcRef((int) hubRef);
                        if (hubGc instanceof WasmStruct hub) {
                            // Try to find class name string in hub fields
                            for (int hi = 0; hi <= 15; hi++) {
                                try {
                                    long hf = hub.field(hi);
                                    if (hf >= 0x10000) {
                                        try {
                                            String s = extractStringViaExport(instance, hf);
                                            if (s.contains(".")
                                                    || s.contains("Exception")
                                                    || s.contains("Error")) {
                                                System.err.println(
                                                        "  Exception class (hub field "
                                                                + hi
                                                                + "): "
                                                                + s);
                                            }
                                        } catch (Exception ignored2) {
                                        }
                                    }
                                } catch (Exception ignored2) {
                                    break;
                                }
                            }
                        }
                    } catch (Exception ignored2) {
                    }
                    // Dump all fields with string values
                    for (int fi = 0; fi <= 15; fi++) {
                        try {
                            long fieldRef = excStruct.field(fi);
                            if (fieldRef >= 0x10000) {
                                try {
                                    String msg = extractStringViaExport(instance, fieldRef);
                                    System.err.println(
                                            "  exc.field(" + fi + ") string: \"" + msg + "\"");
                                } catch (Exception ignored2) {
                                }
                            }
                        } catch (Exception e) {
                            break;
                        }
                    }
                }
            } catch (Exception ignored) {
            }
            dumpStruct(instance, "exception", excRef, 0);
        } catch (Throwable e) {
            System.err.println("Error: " + e.getClass().getName() + ": " + e.getMessage());
            e.printStackTrace(System.err);
        }

        // Parse buffered stdout for classfile markers and write .class files to disk
        String output = STDOUT_BUFFER.toString();
        int idx = 0;
        while ((idx = output.indexOf("===CLASSFILE:", idx)) >= 0) {
            int nameStart = idx + "===CLASSFILE:".length();
            int nameEnd = output.indexOf("===", nameStart);
            if (nameEnd < 0) break;
            String name = output.substring(nameStart, nameEnd);
            int dataStart = output.indexOf("\n", nameEnd) + 1;
            int dataEnd = output.indexOf("===END===", dataStart);
            if (dataEnd < 0) break;
            String base64 = output.substring(dataStart, dataEnd).trim();
            byte[] classBytes = Base64.getDecoder().decode(base64);
            Path outPath = Path.of(name);
            Files.write(outPath, classBytes);
            System.err.println("Wrote " + outPath + " (" + classBytes.length + " bytes)");
            idx = dataEnd + "===END===".length();
        }
    }

    // ---- Helpers: value extraction ----

    /** Extract a string from a JS value (storeRef ID) or a GC String ref.
     *  Uses the string.tochars export (like the JS glue code does) for reliable extraction. */
    private static String jsValueToString(Instance inst, long ref) {
        Object obj = loadRef(ref);
        if (obj instanceof String s) return s;
        if (obj instanceof char[] chars) return new String(chars);
        if (ref >= 0x10000) {
            // Use string.tochars export (mirrors JS:
            // charArrayToString(proxyCharArray(string.tochars(s))))
            try {
                return extractStringViaExport(inst, ref);
            } catch (Exception e) {
                if (TRACE)
                    System.err.println(
                            "[WARN] extractStringViaExport failed for ref=" + ref + ": " + e);
            }
            // Fallback: direct GC struct access
            try {
                return gcStructToString(inst, ref);
            } catch (Exception e) {
                if (TRACE)
                    System.err.println("[WARN] gcStructToString failed for ref=" + ref + ": " + e);
            }
        }
        return String.valueOf(ref);
    }

    /** Extract string using the string.tochars export (same approach as the JS glue code).
     *  string.tochars returns a Java char[] GC struct; the actual data array is at field(2). */
    private static String extractStringViaExport(Instance inst, long ref) {
        long charArrayStructRef = inst.export("string.tochars").apply(ref)[0];
        WasmGcRef gcRef = inst.gcRef((int) charArrayStructRef);
        // string.tochars returns a Java char[] which is a struct wrapping a WasmArray
        if (gcRef instanceof WasmStruct s) {
            long dataArrayRef = s.field(2);
            WasmGcRef arrGc = inst.gcRef((int) dataArrayRef);
            if (arrGc instanceof WasmArray arr) {
                char[] chars = new char[arr.length()];
                for (int ci = 0; ci < chars.length; ci++) {
                    chars[ci] = (char) (arr.get(ci) & 0xFFFF);
                }
                return new String(chars);
            }
        }
        // Maybe it's directly a WasmArray (unlikely but handle it)
        if (gcRef instanceof WasmArray arr) {
            char[] chars = new char[arr.length()];
            for (int ci = 0; ci < chars.length; ci++) {
                chars[ci] = (char) (arr.get(ci) & 0xFFFF);
            }
            return new String(chars);
        }
        throw new IllegalArgumentException(
                "string.tochars did not return a char array struct: " + gcRef);
    }

    /** Resolve a JS value externref to a Java Object. */
    private static Object jsValueToObject(Instance inst, long ref) {
        if (ref == -1 || ref == 0) return null;
        Object obj = loadRef(ref);
        if (obj != null) return obj;
        if (ref >= 0x10000) {
            try {
                return gcStructToString(inst, ref);
            } catch (Exception ignored) {
            }
        }
        return ref;
    }

    /** Extract a string from a wasm GC String struct. Tries field[2] then scans fields. */
    static String gcStructToString(Instance inst, long ref) {
        WasmGcRef gcRef = inst.gcRef((int) ref);
        if (gcRef instanceof WasmStruct s) {
            // Try field(2) first (standard String layout)
            for (int fi : new int[] {2, 1, 3, 0}) {
                try {
                    long arrayRef = s.field(fi);
                    WasmGcRef arrGc = inst.gcRef((int) arrayRef);
                    if (arrGc instanceof WasmArray arr
                            && arr.length() > 0
                            && arr.length() < 100000) {
                        char[] chars = new char[arr.length()];
                        for (int ci = 0; ci < chars.length; ci++) {
                            chars[ci] = (char) (arr.get(ci) & 0xFFFF);
                        }
                        return new String(chars);
                    }
                } catch (Exception ignored) {
                }
            }
        }
        throw new IllegalArgumentException(
                "Not a GC String struct: ref=" + ref + " gcRef=" + gcRef);
    }

    /** Create a wasm GC String struct from a Java String. */
    private static long javaStringToGcRef(Instance inst, String s) {
        var arrayCharCreate = inst.export("array.char.create");
        var arrayCharWrite = inst.export("array.char.write");
        var stringFromChars = inst.export("string.fromchars");
        long charArray = arrayCharCreate.apply(s.length())[0];
        for (int i = 0; i < s.length(); i++) {
            arrayCharWrite.apply(charArray, i, (int) s.charAt(i));
        }
        return stringFromChars.apply(charArray)[0];
    }

    private static void dumpStruct(Instance inst, String label, long ref, int depth) {
        if (depth > 5) return;
        String indent = "  ".repeat(depth);
        try {
            WasmGcRef gcRef = inst.gcRef((int) ref);
            if (gcRef instanceof WasmStruct ws) {
                System.err.println(indent + label + " [struct ref=" + ref + "]:");
                for (int fi = 0; fi < 8; fi++) {
                    try {
                        long fv = ws.field(fi);
                        WasmGcRef fg = inst.gcRef((int) fv);
                        if (fg instanceof WasmArray wa) {
                            if (wa.length() < 500) {
                                char[] chars = new char[wa.length()];
                                for (int ci = 0; ci < chars.length; ci++)
                                    chars[ci] = (char) (wa.get(ci) & 0xFFFF);
                                System.err.println(
                                        indent
                                                + "  field("
                                                + fi
                                                + ") = \""
                                                + new String(chars)
                                                + "\"");
                            } else {
                                System.err.println(
                                        indent
                                                + "  field("
                                                + fi
                                                + ") = [array len="
                                                + wa.length()
                                                + "]");
                            }
                        } else if (fg instanceof WasmStruct) {
                            dumpStruct(inst, "field(" + fi + ")", fv, depth + 1);
                        } else {
                            System.err.println(
                                    indent + "  field(" + fi + ") = " + fv + " (gcRef=" + fg + ")");
                        }
                    } catch (Exception ex) {
                        try {
                            System.err.println(indent + "  field(" + fi + ") = " + ws.field(fi));
                        } catch (Exception ex2) {
                            break;
                        }
                    }
                }
            } else if (gcRef instanceof WasmArray wa) {
                System.err.println(
                        indent + label + " [array ref=" + ref + " len=" + wa.length() + "]");
            } else {
                System.err.println(indent + label + " ref=" + ref + " gcRef=" + gcRef);
            }
        } catch (Exception ex) {
            System.err.println(indent + label + " ref=" + ref + " (not a gcref)");
        }
    }

    private static int toInt(Object obj) {
        if (obj instanceof Number n) return n.intValue();
        return 0;
    }

    private static byte toByte(Object obj) {
        if (obj instanceof Number n) return n.byteValue();
        return 0;
    }

    private static long d2l(double d) {
        return Double.doubleToRawLongBits(d);
    }

    private static double l2d(long l) {
        return Double.longBitsToDouble(l);
    }

    /** Find an import name by substring match. Returns null if not found. */
    private static String findImport(WasmModule module, String substring) {
        var importSection = module.importSection();
        for (int i = 0; i < importSection.importCount(); i++) {
            var imp = importSection.getImport(i);
            if (imp.name().contains(substring)) {
                return imp.name();
            }
        }
        return null;
    }

    static boolean TRACE = Boolean.getBoolean("trace");

    /** Create a HostFunction using the wasm module's actual import type. Returns null if import not found. */
    private static HostFunction fni(
            String mod,
            String name,
            Map<String, FunctionType> importTypes,
            WasmFunctionHandle handle) {
        var type = importTypes.get(name);
        if (type == null) return null; // import doesn't exist in this wasm module
        WasmFunctionHandle traced =
                (inst, args) -> {
                    if (TRACE)
                        System.err.println(
                                "[CALL] " + name + " args=" + java.util.Arrays.toString(args));
                    var result = handle.apply(inst, args);
                    if (TRACE)
                        System.err.println(
                                "[RET]  " + name + " -> " + java.util.Arrays.toString(result));
                    return result;
                };
        return new HostFunction(mod, name, type, traced);
    }

    /** Like fni but finds the import name by substring first. Returns null if not found. */
    private static HostFunction fnf(
            String mod,
            WasmModule module,
            String substring,
            Map<String, FunctionType> importTypes,
            WasmFunctionHandle handle) {
        String name = findImport(module, substring);
        if (name == null) return null;
        return fni(mod, name, importTypes, handle);
    }
}
