<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.dylibso.chicory</groupId>
    <artifactId>chicory</artifactId>
    <version>999-SNAPSHOT</version>
  </parent>
  <artifactId>test-javac</artifactId>
  <packaging>jar</packaging>

  <name>Chicory - Compile Javac</name>

  <properties>
    <maven.compiler.release>25</maven.compiler.release>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.dylibso.chicory</groupId>
      <artifactId>runtime</artifactId>
    </dependency>
    <dependency>
      <groupId>com.dylibso.chicory</groupId>
      <artifactId>wasm</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>com.dylibso.chicory</groupId>
        <artifactId>chicory-compiler-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>compile-javac</id>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <name>com.example.metacircular.Javac</name>
              <wasmFile>/home/andreatp/workspace/metacircular-java-wasm/example3.1/javac/target/javac.opt3.js.wasm</wasmFile>
              <!-- working version: <wasmFile>/home/andreatp/workspace/metacircular-java-wasm/example3.1/javac/target/javac.js.wasm</wasmFile> -->
              <interpreterFallback>WARN</interpreterFallback>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
