name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        version: [11]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Checkout wasi-testsuite
        uses: actions/checkout@v4
        with:
          repository: WebAssembly/wasi-testsuite
          path: wasi-testsuite
          ref: prod/testsuite-base
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.version }}'
          cache: maven
      - name: Compile Java
        run: mvn -B -q clean install -DskipTests
      - name: Test WASI
        run: mvn -B clean verify -pl wasi '-Dtest=SuiteCTest#testFdopendirWithAccess,SuiteRustTest#testPathRename,SuiteRustTest#testRemoveNonemptyDirectory'
