name: Perf

on:
  # TODO: fix me
  push:

jobs:
  perf:
    name: Run JMH tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources for this branch
        uses: actions/checkout@v4
      - name: Checkout sources from main
        uses: actions/checkout@v4
        with:
          # TODO: switch to main after it get merged
          ref: initial-jmh
          path: main
      - name: Checkout testsuite
        uses: actions/checkout@v4
        with:
          repository: WebAssembly/testsuite
          path: testsuite
          # The ref needs to stay in sync with the default value in test-gen-plugin
          ref: c2a67a575ddc815ff2212f68301d333e5e30a923
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build JMH jars
        run: ./scripts/build-jmh.sh
      - name: Build JMH jars on main
        working-directory: main
        run: ./scripts/build-jmh.sh
      - name: Run JMH
        run: ./scripts/run-jmh.sh
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: results
          path: jmh-result.json
      - name: Run JMH on main
        working-directory: main
        run: ./scripts/run-jmh.sh
      - uses: actions/upload-artifact@v4
        id: main-artifact-upload-step
        with:
          name: results
          path: main/jmh-result.json
      # Artifacts are uploaded as zip files... need to automate the generation of the JMH results
      - name: Produce a link to the visualization
        run: echo "./scripts/show-results.sh ${{ steps.main-artifact-upload-step.outputs.artifact-id }} ${{ steps.main-artifact-upload-step.outputs.artifact-id }}"
